name: Setup Node
description: Setup node and cache node_modules
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install JS dependencies
      shell: bash
      run: yarn install --frozen-lockfile
