name: Build Android

on:
  pull_request: 
    types: ['labeled']

jobs:
  build-android:
    if: contains(github.event.pull_request.labels.*.name, 'android-build')
  
    name: Build Android
    runs-on: ubuntu-latest

    env:
      JAVA_OPTS: "-Xms512m -Xmx2g"
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
      TERM: dumb

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11.0.14
          cache: "gradle"

      - name: Generate assets
        run: npx react-native bundle --platform android --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App APK
        run: |
          cd android && ./gradlew bundleExperimentalPlayDebug --no-daemon
