name: Build Android Experimental

on:
  pull_request: 
    types: ['labeled']

jobs:
  build-android:
    if: contains(github.event.pull_request.labels.*.name, 'android-build')
  
    name: Build Android Experimental
    runs-on: ubuntu-latest
    environment: EXPERIMENTAL

    env:
      JAVA_OPTS: "-Xms512m -Xmx2g"
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
      TERM: dumb

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Decode Keystore
        run: echo ${{ secrets.KEYSTORE_BASE_64 }} | base64 -d > ./android/app/key.keystore

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11.0.14
          cache: "gradle"

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Set gradle.properties
        run: |
            echo -e "" > ./android/gradle.properties
            echo -e android.useAndroidX=true >> ./android/gradle.properties
            echo -e android.enableJetifier=true >> ./android/gradle.properties
            echo -e FLIPPER_VERSION=0.51.0 >> ./android/gradle.properties
            echo -e VERSIONCODE=${{ github.run_number }} >> ./android/gradle.properties
            echo -e APPLICATION_ID=chat.rocket.reactnative >> ./android/gradle.properties
            echo -e BugsnagAPIKey=${{ secrets.BUGSNAG_KEY }} >> ./android/gradle.properties
            echo -e KEYSTORE=${{ secrets.KEYSTORE }} >> ./android/gradle.properties
            echo -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> ./android/gradle.properties
            echo -e KEY_ALIAS=${{ secrets.KEY_ALIAS }} >> ./android/gradle.properties
            echo -e KEY_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> ./android/gradle.properties     

      - name: Generate App APK
        run: |
          cd android && ./gradlew bundleExperimentalPlayRelease --no-daemon
