workflows:
  rocketchat_apk:
    name: Build Rocket.Chat Android APK
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      vars:
        GRADLE_OPTS: '-Xmx4096m'
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
