name: Generate Version Code
description: Generates version code from GitHub run number

inputs:
  official:
    type: boolean
    required: true
  os:
    type: string
    required: true
  FASTLANE_GOOGLE_SERVICE_ACCOUNT:
    type: string
    required: true
  APP_STORE_CONNECT_API_KEY_BASE64:
    type: string
    required: true
  MATCH_KEYCHAIN_NAME:
    type: string
    required: false
  MATCH_KEYCHAIN_PASSWORD:
    type: string
    required: false
  MATCH_PASSWORD:
    type: string
    required: false
  APP_STORE_CONNECT_API_KEY_ID:
    type: string
    required: false
  APP_STORE_CONNECT_API_KEY_ISSUER_ID:
    type: string
    required: false
  FASTLANE_REPO_PAT:
    type: string
    required: false

outputs:
  VERSIONCODE:
    description: "Generated version code"
    value: ${{ steps.compute.outputs.VERSIONCODE }}

runs:
  using: "composite"
  steps:
    - name: Set up Xcode
      if: ${{ inputs.os == 'ios' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
        bundler-cache: true

    - name: Install Fastlane
      if: ${{ inputs.os == 'android' }}
      working-directory: android
      run: |
        bundle install --path gems
      shell: bash

    - name: Store the Google service account key
      if: ${{ inputs.os == 'android' }}
      working-directory: android
      run: |
        echo "${{ inputs.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
      shell: bash

    - name: Decode p8
      if: ${{ inputs.os == 'ios' }}
      run: |
        echo ${{ inputs.APP_STORE_CONNECT_API_KEY_BASE64 }} | base64 --decode > ./ios/fastlane/app_store_connect_api_key.p8
      shell: bash

    - name: Compute VERSIONCODE (iOS)
      id: compute-versioncode-ios
      if: ${{ inputs.os == 'ios' }}
      shell: bash
      run: |
        VERSIONCODE=$(bundle exec fastlane ios get_testflight_version | tail -n1)
        echo "LATEST_VERSIONCODE=$VERSIONCODE" >> $GITHUB_OUTPUT
      working-directory: ios
      env:
        MATCH_KEYCHAIN_NAME: ${{ inputs.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ inputs.MATCH_KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ inputs.MATCH_PASSWORD }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ inputs.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        FASTLANE_REPO_PAT: ${{ inputs.FASTLANE_REPO_PAT }}

    - name: Compute VERSIONCODE (Android)
      id: compute-versioncode-android
      if: ${{ inputs.os == 'android' }}
      shell: bash
      run: |
        VERSIONCODE=$(bundle exec fastlane android version_code | tail -n1)
        echo "LATEST_VERSIONCODE=$VERSIONCODE" >> $GITHUB_OUTPUT
      working-directory: android

    - name: Compute VERSIONCODE
      id: compute
      shell: bash
      env:
        LATEST_VERSIONCODE: ${{ steps.compute-versioncode-ios.outputs.LATEST_VERSIONCODE }} || ${{ steps.compute-versioncode-android.outputs.LATEST_VERSIONCODE }}
      run: |
        VERSIONCODE=$((LATEST_VERSIONCODE + 1))
        echo "VERSIONCODE=$VERSIONCODE" >> $GITHUB_OUTPUT

        echo "### 📦 Version Code Generated" >> $GITHUB_STEP_SUMMARY
        echo "\`Version Code: $VERSIONCODE\`" >> $GITHUB_STEP_SUMMARY