name: Generate Version Code
description: Generates version code

inputs:
  RN_VARIABLES_PAT:
    required: true
    type: string

outputs:
  VERSIONCODE:
    description: "Generated version code"
    value: ${{ steps.compute.outputs.VERSIONCODE }}

runs:
  using: "composite"
  steps:
    - name: Get BUILD_VERSION from repo variable
      id: build_version
      shell: bash
      run: |
        RESPONSE=$(
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.RN_VARIABLES_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/BUILD_VERSION
        )

        VALUE=$(echo "$RESPONSE" | jq -r '.value')
        echo "LATEST_BUILD_VERSION=$VALUE" >> $GITHUB_OUTPUT

    - name: Compute BUILD_VERSION
      id: compute
      shell: bash
      run: |
        LATEST_VERSIONCODE="${{ steps.versioncode.outputs.LATEST_BUILD_VERSION }}"
        VERSIONCODE=$((LATEST_VERSIONCODE + 1))
        echo "VERSIONCODE=$VERSIONCODE" >> $GITHUB_OUTPUT

        echo "### 📦 Version Code Generated" >> $GITHUB_STEP_SUMMARY
        echo "\`Version Code: $VERSIONCODE\`" >> $GITHUB_STEP_SUMMARY

    - name: Update BUILD_VERSION in repo variable
      shell: bash
      run: |
        curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.RN_VARIABLES_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -X PATCH \
          -d '{"name": "BUILD_VERSION", "value": "${{ steps.compute.outputs.VERSIONCODE }}"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/BUILD_VERSION
