import { IMessage, TMessageModel } from '../../../definitions';

export const parseModelMessageToMessage = (messageModel: TMessageModel): IMessage =>
	({
		msg: messageModel.msg,
		t: messageModel.t,
		ts: messageModel.ts,
		u: messageModel.u,
		subscription: messageModel.subscription,
		alias: messageModel.alias,
		parseUrls: messageModel.parseUrls,
		groupable: messageModel.groupable,
		avatar: messageModel.avatar,
		emoji: messageModel.emoji,
		attachments: messageModel.attachments,
		urls: messageModel.urls,
		_updatedAt: messageModel._updatedAt,
		status: messageModel.status,
		pinned: messageModel.pinned,
		starred: messageModel.starred,
		editedBy: messageModel.editedBy,
		reactions: messageModel.reactions,
		role: messageModel.role,
		drid: messageModel.drid,
		dcount: messageModel.dcount,
		dlm: messageModel.dlm,
		tmid: messageModel.tmid,
		tcount: messageModel.tcount,
		tlm: messageModel.tlm,
		replies: messageModel.replies,
		mentions: messageModel.mentions,
		channels: messageModel.channels,
		unread: messageModel.unread,
		autoTranslate: messageModel.autoTranslate,
		translations: messageModel.translations,
		tmsg: messageModel.tmsg,
		blocks: messageModel.blocks,
		e2e: messageModel.e2e,
		tshow: messageModel.tshow,
		md: messageModel.md,
		comment: messageModel.comment
	} as IMessage);
