export const FLOATING_ACTION_BUTTON_SIZE = 56;
export const FLOATING_ACTION_BUTTON_MARGIN = 16;
export const FLOATING_ACTION_BUTTON_CLEARANCE = FLOATING_ACTION_BUTTON_SIZE + FLOATING_ACTION_BUTTON_MARGIN * 2;
