name: 'Upload Android'
description: 'Downloads AAB + Manifest, uploads to Play Store'
inputs:
  type:
    description: 'Build type: official or experimental'
    required: true
  FASTLANE_GOOGLE_SERVICE_ACCOUNT:
    description: 'Google service account key for upload'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for commenting'
    required: true
  BUILD_VERSION:
    description: 'Build version for build'
    required: true
  trigger:
    description: 'Trigger for build'
    required: true
    default: pr
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Experimental AAB
      if: ${{ inputs.type == 'experimental' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab-experimental
        path: android/app/build/outputs/bundle/experimentalRelease/

    - name: Download Official AAB
      if: ${{ inputs.type == 'official' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab-official
        path: android/app/build/outputs/bundle/officialRelease/

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
        bundler-cache: true

    - name: Install Fastlane
      working-directory: android
      run: |
        bundle install --path gems
      shell: bash

    - name: Store the Google service account key
      working-directory: android
      run: |
        echo "${{ inputs.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
      shell: bash

    - name: Generate shared release changelog
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)

        git log "$LAST_TAG"..HEAD --pretty=format:"- %s" > changelog.txt

        if [ ! -s changelog.txt ]; then
          echo "- Improvements and bug fixes" > changelog.txt
        fi
      shell: bash

    - name: Save changelog
      uses: actions/upload-artifact@v4
      with:
        name: Android Changelog
        path: changelog.txt

    - name: Fastlane Play Store Upload
      working-directory: android
      run: |
        if [[ ${{ inputs.trigger }} == "pr" ]]; then
          bundle exec fastlane android official_open_testing
          # bundle exec fastlane android beta official:${{ inputs.type == 'official' }}
        fi
        if [[ ${{ inputs.trigger }} == "develop" ]] && [[ ${{ inputs.type }} == 'experimental' ]]; then
          bundle exec fastlane android experimental_production
        fi
        if [[ ${{ inputs.trigger }} == "develop" ]] && [[ ${{ inputs.type }} == 'official' ]]; then
          bundle exec fastlane android official_open_testing
        fi
          
      shell: bash
    
    - name: Leave a comment on PR
      if: ${{ inputs.trigger == 'pr' }}
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BUILD_TYPE: ${{ inputs.type }}
        BUILD_VERSION: ${{ inputs.BUILD_VERSION }}
      run: |
        if [[ "$BUILD_TYPE" == "official" ]]; then
          app_name="Rocket.Chat"
        else
          app_name="Rocket.Chat Experimental"
        fi

        gradle_file="android/app/build.gradle"
        VERSION_NAME=$(grep versionName $gradle_file | head -n 1 | sed -E 's/.*versionName[[:space:]]+"([^"]+)".*/\1/')

        version_info="$app_name $VERSION_NAME.$BUILD_VERSION"

        message="**Android Build Available**"$'\n\n'"$version_info"

        gh pr comment "$PR_NUMBER" --body "$message"
      shell: bash