name: 'Upload Android'
description: 'Downloads AAB + Manifest, uploads to Play Store, and handles Bugsnag'
inputs:
  type:
    description: 'Build type: official or experimental'
    required: true
  FASTLANE_GOOGLE_SERVICE_ACCOUNT:
    description: 'Google service account key for upload'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Download Experimental AAB
      if: ${{ inputs.type == 'experimental' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/experimentalRelease/app-experimental-release.aab

    - name: Download Official AAB
      if: ${{ inputs.type == 'official' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/officialRelease/app-official-release.aab

    - name: Download Experimental Manifest
      if: ${{ inputs.type == 'experimental' }}
      uses: actions/download-artifact@v4
      with:
        name: android-manifest
        path: android/app/build/intermediates/merged_manifests/experimentalRelease/processExperimentalReleaseManifest/AndroidManifest.xml

    - name: Download Official Manifest
      if: ${{ inputs.type == 'official' }}
      uses: actions/download-artifact@v4
      with:
        name: android-manifest
        path: android/app/build/intermediates/merged_manifests/officialRelease/processOfficialReleaseManifest/AndroidManifest.xml

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
        bundler-cache: true

    - name: Install Fastlane
      working-directory: android
      run: |
        bundle install --path gems
      shell: bash

    - name: Upload sourcemaps/NDK symbols to Bugsnag (Only for experimental)
      if: ${{ inputs.type == 'experimental' }}
      run: |
        yarn bugsnag:upload-android --variant experimentalRelease --app-manifest android/app/build/intermediates/merged_manifests/experimentalRelease/processExperimentalReleaseManifest/AndroidManifest.xml
        yarn bugsnag-cli upload android-aab android/app/build/outputs/bundle/experimentalRelease/app-experimental-release.aab
      shell: bash

    - name: Store the Google service account key
      working-directory: android
      run: |
        echo "${{ inputs.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
      shell: bash

    - name: Fastlane Play Store Upload
      working-directory: android
      run: |
        bundle exec fastlane android internal_app_sharing
      shell: bash
