name: 'Upload Android'
description: 'Downloads AAB + Manifest, uploads to Play Store, and handles Bugsnag'
inputs:
  type:
    description: 'Build type: official or experimental'
    required: true
  FASTLANE_GOOGLE_SERVICE_ACCOUNT:
    description: 'Google service account key for upload'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Download Experimental AAB
      if: ${{ inputs.type == 'experimental' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/experimentalRelease/

    - name: Download Official AAB
      if: ${{ inputs.type == 'official' }}
      uses: actions/download-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/officialRelease/

    - name: List downloaded files
      run: ls -R android/app/build/outputs/bundle
      shell: bash

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
        bundler-cache: true

    - name: Install Fastlane
      working-directory: android
      run: |
        bundle install --path gems
      shell: bash

    - name: Store the Google service account key
      working-directory: android
      run: |
        echo "${{ inputs.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
      shell: bash

    - name: Fastlane Play Store Upload
      run: |
        cd android
        bundle exec fastlane android internal_app_sharing
      shell: bash
