import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
	version: 13,
	tables: [
		tableSchema({
			name: 'subscriptions',
			columns: [
				{ name: '_id', type: 'string' },
				{ name: 'f', type: 'boolean' },
				{ name: 't', type: 'string' },
				{ name: 'ts', type: 'number' },
				{ name: 'ls', type: 'number' },
				{ name: 'name', type: 'string' },
				{ name: 'fname', type: 'string' },
				{ name: 'rid', type: 'string', isIndexed: true },
				{ name: 'open', type: 'boolean' },
				{ name: 'alert', type: 'boolean' },
				// roles: 'string[]',
				{ name: 'unread', type: 'number' },
				{ name: 'user_mentions', type: 'number' },
				{ name: 'room_updated_at', type: 'number' },
				{ name: 'ro', type: 'boolean' },
				{ name: 'last_open', type: 'number', isOptional: true },
				// { name: 'last_message_id', type: 'string', isIndexed: true },
				{ name: 'last_message', type: 'string', isOptional: true },
				{ name: 'description', type: 'string', isOptional: true },
				{ name: 'announcement', type: 'string', isOptional: true },
				{ name: 'topic', type: 'string', isOptional: true },
				{ name: 'blocked', type: 'boolean', isOptional: true },
				{ name: 'blocker', type: 'boolean', isOptional: true },
				{ name: 'react_when_read_only', type: 'boolean', isOptional: true },
				{ name: 'archived', type: 'boolean', isOptional: true },
				{ name: 'join_code_required', type: 'boolean', isOptional: true },
				// { name: 'notifications', type: 'boolean', isOptional: true },
				// { name: 'muted', type: 'string', isOptional: true },
				{ name: 'broadcast', type: 'boolean', isOptional: true },
				{ name: 'prid', type: 'string', isOptional: true },
				{ name: 'draft_message', type: 'string', isOptional: true },
				{ name: 'last_thread_sync', type: 'number', isOptional: true },
				{ name: 'auto_translate', type: 'boolean', isOptional: true },
				{ name: 'auto_translate_language', type: 'string' }
			]
		}),
		tableSchema({
			name: 'messages',
			columns: [
				{ name: 'msg', type: 'string', isOptional: true },
				{ name: 't', type: 'string', isOptional: true },
				{ name: 'rid', type: 'string', isIndexed: true },
				// { name: 'subscription_id', type: 'string', isIndexed: true },
				{ name: 'ts', type: 'number' },
				{ name: 'u', type: 'string' },
				{ name: 'alias', type: 'string' },
				{ name: 'parse_urls', type: 'string' },
				{ name: 'groupable', type: 'boolean', isOptional: true },
				{ name: 'avatar', type: 'string', isOptional: true },
				{ name: 'attachments', type: 'string', isOptional: true },
				{ name: 'urls', type: 'string', isOptional: true },
				{ name: '_updated_at', type: 'number' },
				{ name: 'status', type: 'number', isOptional: true },
				{ name: 'pinned', type: 'boolean', isOptional: true },
				{ name: 'starred', type: 'boolean', isOptional: true },
				{ name: 'edited_by', type: 'string', isOptional: true },
				{ name: 'reactions', type: 'string', isOptional: true },
				{ name: 'role', type: 'string', isOptional: true },
				{ name: 'drid', type: 'string', isOptional: true },
				{ name: 'dcount', type: 'number', isOptional: true },
				{ name: 'dlm', type: 'number', isOptional: true },
				{ name: 'tmid', type: 'string', isOptional: true },
				{ name: 'tcount', type: 'number', isOptional: true },
				{ name: 'tlm', type: 'number', isOptional: true },
				{ name: 'replies', type: 'string', isOptional: true },
				{ name: 'mentions', type: 'string', isOptional: true },
				{ name: 'channels', type: 'string', isOptional: true },
				{ name: 'unread', type: 'boolean', isOptional: true },
				{ name: 'auto_translate', type: 'boolean', isOptional: true },
				{ name: 'translations', type: 'string', isOptional: true },
				{ name: 'tmsg', type: 'string', isOptional: true }
			]
		}),
		tableSchema({
			name: 'threads',
			columns: [
				{ name: 'msg', type: 'string', isOptional: true },
				{ name: 't', type: 'string', isOptional: true },
				{ name: 'rid', type: 'string', isIndexed: true },
				// { name: 'subscription_id', type: 'string', isIndexed: true },
				{ name: 'ts', type: 'number' },
				{ name: 'u', type: 'string' },
				{ name: 'alias', type: 'string', isOptional: true },
				{ name: 'parse_urls', type: 'string', isOptional: true },
				{ name: 'groupable', type: 'boolean', isOptional: true },
				{ name: 'avatar', type: 'string', isOptional: true },
				{ name: 'attachments', type: 'string', isOptional: true },
				{ name: 'urls', type: 'string', isOptional: true },
				{ name: 'updated_at', type: 'number' },
				{ name: 'status', type: 'number', isOptional: true },
				{ name: 'pinned', type: 'boolean', isOptional: true },
				{ name: 'starred', type: 'boolean', isOptional: true },
				{ name: 'edited_by', type: 'string', isOptional: true },
				{ name: 'reactions', type: 'string', isOptional: true },
				{ name: 'role', type: 'string', isOptional: true },
				{ name: 'drid', type: 'string', isOptional: true },
				{ name: 'dcount', type: 'number', isOptional: true },
				{ name: 'dlm', type: 'number', isOptional: true },
				{ name: 'tmid', type: 'string', isOptional: true },
				{ name: 'tcount', type: 'number', isOptional: true },
				{ name: 'replies', type: 'string', isOptional: true },
				{ name: 'mentions', type: 'string', isOptional: true },
				{ name: 'channels', type: 'string', isOptional: true },
				{ name: 'unread', type: 'boolean', isOptional: true },
				{ name: 'auto_translate', type: 'boolean', isOptional: true },
				{ name: 'translations', type: 'string', isOptional: true }
			]
		}),
		tableSchema({
			name: 'thread_messages',
			columns: [
				{ name: 'msg', type: 'string', isOptional: true },
				{ name: 't', type: 'string', isOptional: true },
				{ name: 'rid', type: 'string', isIndexed: true },
				// { name: 'subscription_id', type: 'string', isIndexed: true },
				{ name: 'ts', type: 'number' },
				{ name: 'u', type: 'string' },
				{ name: 'alias', type: 'string', isOptional: true },
				{ name: 'parse_urls', type: 'string', isOptional: true },
				{ name: 'groupable', type: 'boolean', isOptional: true },
				{ name: 'avatar', type: 'string', isOptional: true },
				{ name: 'attachments', type: 'string', isOptional: true },
				{ name: 'urls', type: 'string', isOptional: true },
				{ name: 'updated_at', type: 'number' },
				{ name: 'status', type: 'number', isOptional: true },
				{ name: 'pinned', type: 'boolean', isOptional: true },
				{ name: 'starred', type: 'boolean', isOptional: true },
				{ name: 'edited_by', type: 'string', isOptional: true },
				{ name: 'reactions', type: 'string', isOptional: true },
				{ name: 'role', type: 'string', isOptional: true },
				{ name: 'drid', type: 'string', isOptional: true },
				{ name: 'dcount', type: 'number', isOptional: true },
				{ name: 'dlm', type: 'number', isOptional: true },
				{ name: 'tmid', type: 'string', isOptional: true },
				{ name: 'tcount', type: 'number', isOptional: true },
				{ name: 'tlm', type: 'number', isOptional: true },
				{ name: 'replies', type: 'string', isOptional: true },
				{ name: 'mentions', type: 'string', isOptional: true },
				{ name: 'channels', type: 'string', isOptional: true },
				{ name: 'unread', type: 'boolean', isOptional: true },
				{ name: 'auto_translate', type: 'boolean', isOptional: true },
				{ name: 'translations', type: 'string', isOptional: true }
			]
		}),
		tableSchema({
			name: 'user',
			columns: [
				{ name: 'id', type: 'string' }
			]
		})
	]
});
