appId: chat.rocket.reactnative
flows:
  - onboarding/workspace/invalid_workspace.yaml
excludeTags:
  - 'skip'
  - 'utill'
executionOrder:
  continueOnFailure: true
  flowsOrder:
    - onboarding/workspace/valid_workspace.yaml
    - onboarding/workspace/invalid_workspace.yaml
    - onboarding/legal.yaml
    - onboarding/login/login.yaml
    - onboarding/login/invalid_credentials.yaml
    - onboarding/register/email_used.yaml
    - onboarding/register/username_used.yaml
    - onboarding/register/create_account.yaml
    - onboarding/forgot_password.yaml
    - onboarding/roomslist.yaml
    - onboarding/server_history.yaml
