name: iOS CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/ios_experimental_build.yml
    secrets:
      APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
      BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      FASTLANE_REPO_PAT: ${{ secrets.FASTLANE_REPO_PAT }}

  test:
    uses: ./.github/workflows/maestro_ios.yml
    needs: build