name: Build Android Experimental APK

on:
  workflow_call:
    secrets:
      EXPERIMENTAL_KEYSTORE_BASE64:
        required: true
      EXPERIMENTAL_KEYSTORE_PASSWORD:
        required: true
      EXPERIMENTAL_KEY_ALIAS:
        required: true
      EXPERIMENTAL_KEY_PASSWORD:
        required: true


jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Log the secrets
        run: |
          if [ -z "${{ secrets.EXPERIMENTAL_KEYSTORE_BASE64 }}" ]; then
            echo "❌ EXPERIMENTAL_KEYSTORE_BASE64 is NOT set"
          else
            echo "✅ EXPERIMENTAL_KEYSTORE_BASE64 is set"
          fi

          if [ -z "${{ secrets.EXPERIMENTAL_KEYSTORE_PASSWORD }}" ]; then
            echo "❌ EXPERIMENTAL_KEYSTORE_PASSWORD is NOT set"
          else
            echo "✅ EXPERIMENTAL_KEYSTORE_PASSWORD is set"
          fi

          if [ -z "${{ secrets.EXPERIMENTAL_KEY_ALIAS }}" ]; then
            echo "❌ EXPERIMENTAL_KEY_ALIAS is NOT set"
          else
            echo "✅ EXPERIMENTAL_KEY_ALIAS is set"
          fi

          if [ -z "${{ secrets.EXPERIMENTAL_KEY_PASSWORD }}" ]; then
            echo "❌ EXPERIMENTAL_KEY_PASSWORD is NOT set"
          else
            echo "✅ EXPERIMENTAL_KEY_PASSWORD is set"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Decode Keystore
        run: |
          echo "${{ secrets.EXPERIMENTAL_KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Set gradle.properties
        run: |
          echo " " >> android/gradle.properties
          echo "KEYSTORE=release.keystore" >> android/gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.EXPERIMENTAL_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "KEY_ALIAS=${{ secrets.EXPERIMENTAL_KEY_ALIAS }}" >> android/gradle.properties
          echo "KEY_PASSWORD=${{ secrets.EXPERIMENTAL_KEY_PASSWORD }}" >> android/gradle.properties
      
      - name: Install Dependencies
        run: yarn install

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Gradle Caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Android build output 
        uses: actions/cache@v4
        with:
          path: |
            android/app/build
          key: build-output-${{ hashFiles('android/app/src/**', '**/*.gradle*') }}
          restore-keys: |
            build-output-

      - name: Build Android Release APK
        run: |
          cd android
          ./gradlew assembleExperimentalRelease --no-daemon --build-cache --parallel --max-workers=4

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android Experimental APK
          path: android/app/build/outputs/apk/experimental/release/app-experimental-release.apk