name: Build Develop

permissions:
  contents: read

on:
  push:
    branches:
      - 'chore.gh-build-patch'

jobs:
  run-eslint-and-test:
    name: ESLint and Test
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/eslint.yml

  android-build-experimental-store:
    name: Build Android Experimental
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-android.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental
      trigger: develop

  android-build-official-store:
    name: Build Android Official
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-official-android.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: official
      trigger: develop

  ios-build-experimental-store:
    name: Build iOS Experimental
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-ios.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental
      trigger: develop
      
  ios-build-official-store:
    name: Build iOS Official
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-official-ios.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: official
      trigger: develop