name: Build Android And Upload

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true

jobs:
  build-android:
    name: Build
    runs-on: ubuntu-latest
    environment: build_official_android
    steps:
      - name: Validate type input
        run: |
          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
            exit 1
          fi

      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Android
        uses: ./.github/actions/build-android
        with:
          type: official
      
  upload-android:
    name: Upload
    runs-on: ubuntu-latest
    environment: upload_official_android
    needs: build-android
    steps:
      - name: Validate type input
        run: |
          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Upload Android
        uses: ./.github/actions/upload-android
        with:
          type: official