name: Build Android And Upload

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true

jobs:
  build-hold:
    name: Hold
    runs-on: ubuntu-latest
    environment: official_android_build
    steps:
      - name: Hold
        run: |
          echo "Hold"

  build-android:
    name: Build
    runs-on: ubuntu-latest
    needs: build-hold
    steps:
      - name: Validate type input
        run: |
          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Android
        uses: ./.github/actions/build-android
        with:
          type: official
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
          KEYSTORE_OFFICIAL_BASE64: ${{ secrets.KEYSTORE_OFFICIAL_BASE64 }}
          KEYSTORE_OFFICIAL: ${{ secrets.KEYSTORE_OFFICIAL }}
          KEYSTORE_OFFICIAL_PASSWORD: ${{ secrets.KEYSTORE_OFFICIAL_PASSWORD }}
          KEYSTORE_OFFICIAL_ALIAS: ${{ secrets.KEYSTORE_OFFICIAL_ALIAS }}
          BUGSNAG_KEY_OFFICIAL: ${{ secrets.BUGSNAG_KEY_OFFICIAL }}

  upload-hold:
    name: Upload Hold
    runs-on: ubuntu-latest
    environment: upload_official_android
    needs: [build-android]
    steps:
      - name: Hold
        run: |
          echo "Hold"

  upload-android:
    name: Upload
    runs-on: ubuntu-latest
    needs: [upload-hold]
    steps:
      - name: Validate type input
        run: |
          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Upload Android
        uses: ./.github/actions/upload-android
        with:
          type: official
          FASTLANE_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}
          