name: Build Develop

permissions:
  contents: read

on:
  push:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-eslint-and-test:
    name: ESLint and Test
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/eslint.yml

  generate-changelog:
    name: Generate Release Changelog
    needs: [run-eslint-and-test]
    uses: ./.github/workflows/generate-changelog.yml

  android-build-official-store:
    name: Build Android Official
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-official-android.yml
    needs: [run-eslint-and-test, generate-changelog]
    secrets: inherit
    with:
      trigger: develop

  ios-build-official-store:
    name: Build iOS Official
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-official-ios.yml
    needs: [run-eslint-and-test, generate-changelog]
    secrets: inherit
    with:
      trigger: develop
