name: Build Develop

on:
  push:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  run-eslint-and-test:
    name: ESLint and Test
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    permissions:
      contents: read
    uses: ./.github/workflows/eslint.yml

  generate-changelog:
    name: Generate Release Changelog
    needs: [run-eslint-and-test]
    permissions:
      contents: read
    uses: ./.github/workflows/generate-changelog.yml

  android-build-store:
    name: Build Android
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    permissions:
      contents: read
    uses: ./.github/workflows/build-android.yml
    needs: [run-eslint-and-test, generate-changelog]
    secrets: inherit
    with:
      trigger: develop

  ios-build-store:
    name: Build iOS
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    permissions:
      contents: read
    uses: ./.github/workflows/build-ios.yml
    needs: [run-eslint-and-test, generate-changelog]
    secrets: inherit
    with:
      trigger: develop
