name: Test CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  run-eslint-and-test:
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/eslint.yml

  android-build-experimental-store:
    name: Build Android Experimental Store
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-android.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental

  android-upload-experimental-store:
    name: Upload Android Experimental Store
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/upload-android.yml
    needs: [android-build-experimental-store]
    secrets: inherit
    with:
      type: experimental

  ios-build-experimental-store:
    name: Build iOS Experimental Store
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-ios.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental
      