name: Test CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  run-eslint-and-test:
    name: ESLint and Test
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/eslint.yml

  android-build-experimental-store:
    name: Android Experimental
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-android.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental

  android-build-official-store:
    name: Android Official
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-offical-android.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: official

  ios-build-experimental-store:
    name: Build iOS Experimental Store
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-ios.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: experimental
      
  ios-build-official-store:
    name: Build iOS Official Store
    if: ${{ github.repository == 'RocketChat/Rocket.Chat.ReactNative' }}
    uses: ./.github/workflows/build-official-ios.yml
    needs: [run-eslint-and-test]
    secrets: inherit
    with:
      type: official