name: iOS Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  ios-build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile
    
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      - name: pod install
        run: |
          yarn pod-install

      - name: Decode p8
        run: |
          echo ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }} | base64 --decode > ./ios/fastlane/app_store_connect_api_key.p8

      - name: Set bugsnag key
        run: |
          cd ios
          /usr/libexec/PlistBuddy -c "Set :bugsnag:apiKey ${{ secrets.BUGSNAG_KEY}}" ./RocketChatRN/Info.plist
          /usr/libexec/PlistBuddy -c "Set :bugsnag:apiKey ${{ secrets.BUGSNAG_KEY}}" ./ShareRocketChatRN/Info.plist

      - name: Build iOS app
        run: |
          cd ios
          bundle exec fastlane ios build_experimental_simulator
        env:
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          FASTLANE_REPO_PAT: ${{ secrets.FASTLANE_REPO_PAT }}

      - name: Upload Fastlane gym log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fastlane-gym-log
          path: /Users/runner/Library/Logs/gym/Rocket.Chat Experimental-RocketChatRN.log
  
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: ios/fastlane/build/Build/Products/Debug-iphonesimulator/RocketChatRN.app