name: Simulator Test

on:
  workflow_call:

jobs:
  install-app:
    runs-on: macos-15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download App
        uses: actions/download-artifact@v4
        with:
          name: ios-simulator-app
          path: ios-simulator-app

      - name: Setup E2E Account
        uses: ./.github/actions/e2e-account
        with:
          E2E_ACCOUNT: ${{ secrets.E2E_ACCOUNT }}

      - name: Install Maestro
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          mkdir recording

      - name: Configure Simulator
        run: |
          defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool false
          defaults write com.apple.iphonesimulator ShowSingleTouches 1
          defaults write com.apple.iphonesimulator SlowAnimations -bool false
          defaults write com.apple.iphonesimulator ShowDeviceBezels -bool false
          defaults write com.apple.iphonesimulator DisableShadows -bool true

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 16"
          xcrun simctl bootstatus "iPhone 16" -b
          xcrun simctl list devices | grep Booted

      - name: Get Simulator UDID 
        id: booted-sim
        run: |
          UDID=$(xcrun simctl list devices | grep "iPhone 16 (" | grep "(Booted)" | grep -oE '[A-F0-9-]{36}' | head -n1)
          echo "UDID=$UDID"
          echo "UDID=$UDID" >> $GITHUB_ENV

      - name: Install App
        run: |
          xcrun simctl install $UDID "ios-simulator-app"

      - name: Run Tests
        run: |
          maestro test .maestro --format junit --output maestro-report.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: maestro-report.xml

      - name: Upload Recordings
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Recordings
          path: recording/

      - name: Upload Maestro Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iOS Maestro Logs
          path: ~/.maestro/tests/