name: Maestro Tests on Android

on:
  workflow_call:

jobs:
  android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    #   - name: Download APK
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: Android Experimental APK

      - name: Download apk using curl
        run: |
          curl -L -o "Android_Experimental_APK.zip" "https://productionresultssa4.blob.core.windows.net/actions-results/e39f9a9b-f7a1-41c4-8ee1-ca6a6d0ab007/workflow-job-run-b8ae348d-46ae-595e-8a05-4c301d709ec8/artifacts/73656cb3c9d46138832e413075cef94865bb0b1e8a5d1b419867e97c9bbf5797.zip?rscd=attachment%3B+filename%3D%22Android+Experimental+APK.zip%22&se=2025-08-09T13%3A22%3A16Z&sig=VGALuptqCxk4GPRMo%2F2witKDCSHOZ1BJepqczUkzosE%3D&ske=2025-08-09T23%3A05%3A40Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-08-09T11%3A05%3A40Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-08-09T13%3A12%3A11Z&sv=2025-05-05"
          unzip Android_Experimental_APK.zip

      - name: Setup E2E Account
        uses: ./.github/actions/e2e-account
        with:
          E2E_ACCOUNT: ${{ secrets.E2E_ACCOUNT }}

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
        
      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator and Run Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          disk-size: 4096M
          arch: x86_64
          target: google_apis
          profile: pixel_7_pro
          cores: 4
          ram-size: 4096M
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            mkdir recording
            adb install app-experimental-release.apk
            adb shell monkey -p chat.rocket.reactnative -c android.intent.category.LAUNCHER 1
            sleep 10
            adb shell am force-stop chat.rocket.reactnative
            maestro record .maestro/onboarding/change_password.yaml
            maestro test .maestro --format junit --output maestro-report.xml

      - name: Upload Recordings
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Recordings
          path: recording/

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Android Test Report
          path: maestro-report.xml

      - name: Upload Maestro Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Android Maestro Logs
          path: ~/.maestro/tests/