name: Test and Lint

on: [push]

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test -w 8

      - name: Codecov
        run: yarn codecov
